Change path
getomni/alacritty pull request #1
Opened 2021-05-11 22:19 UTC by joaopealves

**Changes proposed**
In step 1 of activate theme, it says that you must copy omni.yml in the ~ directory, but when we try to follow the step 2 it does't work because the path on the import is incorrect. It indicate that this file is a directory.

2021-05-11 22:51 UTC, zoedsoupe commented
Thank you for the PR!

However your solution don't solve the problem too :/

I searched a bit and found that the path is relative to where you open the terminal emulator!

You can see more information about it in this Alacritty Issue: https://github.com/alacritty/alacritty/issues/4164

2021-05-11 22:53 UTC, Mdsp9070 requested changes

2021-05-11 22:53 UTC, Mdsp9070 commented on INSTALL.md
> +  - /omni.yml
```suggestion
  - /omni.yml
```

The actual solution is to use the absolute path to the file!

Can be relative to your home as: `~//.config/alacritty/<fiile>.yml` or the full path: `/home/<user>/.config/alacritty/<file>.yml`

2021-05-11 23:22 UTC, eulixir commented on INSTALL.md
> +  - /omni.yml
Cool, it's worked in my workspace 😉

2021-05-13 14:40 UTC, Mdsp9070 commented
Thank you for the correction! Could you please squash these two commits into one?

2021-05-13 14:41 UTC, Mdsp9070 approved these changes

2021-05-13 14:42 UTC, merged